import type { Metadata } from 'next';
import { Josefin_Slab } from 'next/font/google';
import './globals.css';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import Container from '@/components/layout/container';

const josefin_slab = Josefin_Slab({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'RateFlix',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br">
      <body className={josefin_slab.className}>
        <Header />
        <Container>{children}</Container>
        <Footer />
      </body>
    </html>
  );
}
